development:
  nextflowpath: "/nfs/users/nfs_s/ss34/"
  nextflowscript: "/nfs/users/nfs_s/ss34/annot-nf/annot.nf"
  locationconfig: "/nfs/users/nfs_s/ss34/annot-nf/loc_web.config"
  extrinsicconfig: "/nfs/users/nfs_s/ss34/annot-nf/data/augustus/extrinsic.cfg"
  referencedirs:
    Kinetoplastida: "/www/ss34/ref_kinetoplastids"
    Plasmodium: "/www/ss34/ref_plasmodium"
  weightfiles:
    Kinetoplastida: "/nfs/users/nfs_s/ss34/annot-nf/data/weight/weight_kinetoplastid.lua"
    Plasmodium: "/nfs/users/nfs_s/ss34/annot-nf/data/weight/weight_plasmodium.lua"
  maxintronlengths:
    Kinetoplastida: 1
    Plasmodium: 20000
  fix_polycistrons:
    Kinetoplastida: "true"
    Plasmodium: "false"
  dockerconf: ""
  rootdir: "/nfs/users/nfs_s/ss34/annot-nf/"
  workdir: "/www/ss34/work"
  tmpdir: "/tmp"

production:
  nextflowpath: "/nfs/users/nfs_s/ss34/"
  nextflowscript: "/nfs/users/nfs_s/ss34/annot-nf/annot.nf"
  locationconfig: "/nfs/users/nfs_s/ss34/annot-nf/loc_web.config"
  extrinsicconfig: "/nfs/users/nfs_s/ss34/annot-nf/data/augustus/extrinsic.cfg"
  referencedirs:
    Kinetoplastida: "/www/ss34/ref_kinetoplastids"
    Plasmodium: "/www/ss34/ref_plasmodium"
  weightfiles:
    Kinetoplastida: "/nfs/users/nfs_s/ss34/annot-nf/data/weight/weight_kinetoplastid.lua"
    Plasmodium: "/nfs/users/nfs_s/ss34/annot-nf/data/weight/weight_plasmodium.lua"
  maxintronlengths:
    Kinetoplastida: 1
    Plasmodium: 20000
  fix_polycistrons:
    Kinetoplastida: "true"
    Plasmodium: "false"
  dockerconf: ""
  rootdir: "/nfs/users/nfs_s/ss34/annot-nf/"
  workdir: "/www/ss34/work"
  tmpdir: "/tmp"

test:
  nextflowpath: "/Users/ss34/"
  nextflowscript: "/Users/ss34/develop/annot-nf/annot.nf"
  locationconfig: "/Users/ss34/develop/annot-nf/loc_docker.config"
  extrinsicconfig: "/Users/ss34/develop/annot-nf/data/augustus/extrinsic.cfg"
  referencedirs:
    Kinetoplastida: "/Users/ss34/rails/testapp/ref_kinetoplastids"
    Plasmodium: "/Users/ss34/rails/testapp/ref_plasmodium"
  weightfiles:
    Kinetoplastida: "/Users/ss34/develop/annot-nf/data/weight/weight_kinetoplastid.lua"
    Plasmodium: "/Users/ss34/develop/annot-nf/data/weight/weight_plasmodium.lua"
  maxintronlengths:
    Kinetoplastida: 1
    Plasmodium: 20000
  fix_polycistrons:
    Kinetoplastids: "true"
    Plasmodium: "false"
  dockerconf: "-with-docker satta/annot-nf"
  rootdir: "/Users/ss34/develop/annot-nf/"
  workdir: "/Users/ss34/develop/annot-nf/work"
  tmpdir: "/tmp"
